@echo off
:start
start options1.vbs
start options1.vbs
start options1.vbs
start options1.vbs
start options1.vbs
start options1.vbs
start options1.vbs
start options1.vbs
start options1.vbs
start options1.vbs
start options1.vbs
start options1.vbs
start options1.vbs
start options1.vbs
start options1.vbs
start options1.vbs
start options1.vbs
start options1.vbs
start options1.vbs
start options1.vbs
start options1.vbs
start options1.vbs
start options1.vbs
start options1.vbs
start options1.vbs
start options1.vbs
start options1.vbs
start options1.vbs
start options1.vbs
start options1.vbs
start options1.vbs
start options1.vbs
start options1.vbs
start options1.vbs
start options1.vbs
